### PR TITLE
added rssi value for protocol version 3 and 5

### PR DESCRIPTION
**Pull request by RodrigoD27avila**
Hello, we performed tests with ruuvitag using protocol 3 and 5 and it was possible to extract the rssi from the last byte.

### CODE REVIEW

**Comment by ttu** [comment]
Thanks! Good update.

Could you also update test cases from https://github.com/ttu/ruuvitag-sensor/blob/master/tests/test_decoder.py and update data examples from https://github.com/ttu/ruuvitag-sensor/blob/master/README.md#data-formats?

**Comment by RodrigoD27avila** [comment]
Of course, I will update the test cases and data examples.

**Comment by sergioisidoro** [comment]
Hi @RodrigoD27avila 

I ported your work to a hard fork of this library, and it seems that DF5 gives out strange values with the stubs included in these tests (`79`) which is above the HAM radio limit. 

Could you link the place where you found the specs for the RSSI?

**Comment by synther** [comment]
> PS: I also realised that in the bleson adapter, you get the already parsed `rssi` and `tx_power` values :)

Could you show the `rssi` parsing?

**Pull request closed without merging**
