### PR TITLE
Do minor updates to README

### PR DESCRIPTION
**Pull request by terop**
Changes:
* Fix syntax error in one example
* Align explanation to actual code
* Switch one URL to use HTTPS

### CODE REVIEW

**Comment by terop** [comment]
I noticed by accident that https://github.com/ttu/ruuvitag-sensor/blob/master/examples/rx.py does not exist anymore and thus the link is broken. I don't know if there is any equivalent example anymore so I won't update it. It would anyway be good if the link was fixed.

**Comment by ttu** [comment]
Thanks for the updates!

rx.py example file was renamed at some point to https://github.com/ttu/ruuvitag-sensor/blob/master/examples/reactive_extensions.py

I will merge this in few days so you can update the link if you have time or I will update it later.

**Comment by ttu** [comment]
Thanks! You can update the link later if I forget to do it :)

**Comment by terop** [comment]
Sorry, I failed to notice your comment until now.

I created a new branch with the broken link fixed, please find it at https://github.com/terop/ruuvitag-sensor/tree/update_readme_again. Feel free to use it if it is useful.

**Pull request merged**
