### PR TITLE
Add reporting of RSSI

### PR DESCRIPTION
**Pull request by terop**
The detection logic is based on the discussion in issue #52 and part of the implementation on PR #136.

I have not tested this with Bleson is as failed miserably in trying to run this with Bleson.

### CODE REVIEW

**Comment by ttu** [comment]
Thanks! Can you also update https://github.com/terop/ruuvitag-sensor/blob/datas_to_data/CHANGELOG.md about this addition?

No worries about Bleson. It has "beta" support and it will be dropped in favor of Bleak (https://github.com/ttu/ruuvitag-sensor/pull/154)

**Comment by terop** [comment]
CHANGELOG updated.

I am not sure if the way I did the RSSI value "reporting" is the best one. Another option would be to always have the `rssi` field but have the value as `None` or something else when the RSSI cannot be determined.
@ttu which way would be better in your opinion?

**Comment by ttu** [comment]
Sorry, didn't have time to check this thoroughly yesterday. Not sure if it can be done like this, but this would be the correct way to handle RSSI data.

* Adapter returns RSSI with rest of the data. So no need to drop rssi bytes off and return it separately in adapter.
* RSSI is parsed in decoder. Add e.g. `_get_rssi` here:
https://github.com/ttu/ruuvitag-sensor/blob/cb5eb319405766a7789511bdc7479455f375d6e6/ruuvitag_sensor/decoder.py#L243
* RSSI data is added to returned decoded data
https://github.com/ttu/ruuvitag-sensor/blob/cb5eb319405766a7789511bdc7479455f375d6e6/ruuvitag_sensor/decoder.py#L268

**Comment by terop** [comment]
I reworked the implementation per the suggestions you gave, please take a look.

**Comment by ttu** [comment]
Looks good 👍 I will test this later next week.

Can you add a test case here with data containing RSSI?
https://github.com/ttu/ruuvitag-sensor/blob/cb5eb319405766a7789511bdc7479455f375d6e6/tests/test_ruuvitag_sensor.py#L43

**Comment by terop** [comment]
Test case added.

**Comment by terop** [comment]
@ttu would you soon be able to check this?

**Review by ttu — APPROVED** [review]

**Comment by ttu** [comment]
Hi and sorry for the delay!

The implementation looks good, but I won't merge this yet, as I want to first create release 2.0. That release will already have plenty of changes, which means possible changes that can cause issues. Therefore will merge this after the release and add it to the next release.

**Comment by terop** [comment]
I see that the 2.0 release has now been done. @ttu would it soon be possible to merge this PR?

**Comment by ttu** [comment]
Merged. Thanks again for the implementation 👍

**Pull request merged**
