### PR TITLE
Disable some pylint and fix mypy warnings

### PR DESCRIPTION
**Pull request by terop**
Some mypy warnings still remain, see below. I was unable to fix them as I am unfamiliar with mypy.

```
ruuvitag_sensor/adapters/dummy.py:34: error: Return type "AsyncGenerator[Tuple[str, str], None]" of "get_data" incompatible with return type "Coroutine[Any, Any, AsyncGenerator[Tuple[str, str], None]]" in supertype "BleCommunicationAsync"
ruuvitag_sensor/adapters/bleak_ble.py:62: error: Return type "AsyncGenerator[Tuple[str, str], None]" of "get_data" incompatible with return type "Coroutine[Any, Any, AsyncGenerator[Tuple[str, str], None]]" in supertype "BleCommunicationAsync"
ruuvitag_sensor/ruuvi.py:114: error: Argument 2 to "_parse_data" of "RuuviTagSensor" has incompatible type "ListProxy[Any]"; expected "List[str]"
ruuvitag_sensor/ruuvi.py:160: error: Argument 2 to "_parse_data" of "RuuviTagSensor" has incompatible type "ListProxy[Any]"; expected "List[str]"
ruuvitag_sensor/ruuvi.py:236: error: Argument 2 to "_parse_data" of "RuuviTagSensor" has incompatible type "ListProxy[Any]"; expected "List[str]"
ruuvitag_sensor/ruuvi_rx.py:79: error: Argument 3 to "submit" of "Executor" has incompatible type "queue.Queue[Any]"; expected "multiprocessing.queues.Queue[Any]"
```

### CODE REVIEW

**Comment by terop** [comment]
Updated list of mypy warnings can be seen below.
```
ruuvitag_sensor/ruuvi.py:114: error: Argument 2 to "_parse_data" of "RuuviTagSensor" has incompatible type "ListProxy[Any]"; expected "List[str]"
ruuvitag_sensor/ruuvi.py:160: error: Argument 2 to "_parse_data" of "RuuviTagSensor" has incompatible type "ListProxy[Any]"; expected "List[str]"
ruuvitag_sensor/ruuvi.py:236: error: Argument 2 to "_parse_data" of "RuuviTagSensor" has incompatible type "ListProxy[Any]"; expected "List[str]"
ruuvitag_sensor/ruuvi_rx.py:79: error: Argument 3 to "submit" of "Executor" has incompatible type "queue.Queue[Any]"; expected "multiprocessing.queues.Queue[Any]"
```

**Comment by ttu** [comment]
Hi! And thanks for the fixes!

Sorry, I had a few changes coming to master, but didn't find time to merge those earlier. Unfortunately because of those you did fixes that were not relevant after those. 

I think we could fix last mypy errors with these:

```
ruuvitag_sensor/ruuvi.py:114: error: Argument 2 to "_parse_data" of "RuuviTagSensor" has incompatible type "ListProxy[Any]"; expected "List[str]"
ruuvitag_sensor/ruuvi.py:160: error: Argument 2 to "_parse_data" of "RuuviTagSensor" has incompatible type "ListProxy[Any]"; expected "List[str]"
ruuvitag_sensor/ruuvi.py:236: error: Argument 2 to "_parse_data" of "RuuviTagSensor" has incompatible type "ListProxy[Any]"; expected "List[str]"
```
could be fixed with:
```py
def _parse_data(ble_data: MacAndRawData, mac_blacklist: ListProxy[str], allowed_macs: List[str] = []) \
```

and for this:
```
ruuvitag_sensor/ruuvi_rx.py:79: error: Argument 3 to "submit" of "Executor" has incompatible type "queue.Queue[Any]"; expected "multiprocessing.queues.Queue[Any]"
```

it seems that correct type for
```py
m = Manager()
q = m.Queue()
```

is not `from multiprocessing.queues import Queue`, but `from queue import Queue`

**Comment by terop** [comment]
I was able to fix  the second of the remaining errors.

Unfortunately I was unable to fix the first one because I was unable to find where `ListProxy` defined. It is somehow related to the `multiprocessing` module but I was again unable to find a definition for it there.

**Comment by ttu** [comment]
Yes, `ListProxy` is in multiprocessing module. Try `from multiprocessing.managers import ListProxy`

**Comment by terop** [comment]
Thanks! That did it, now there is no more warnings from mypy.

**Comment by terop** [comment]
Now there some interesting unit test error. @ttu could you take a look?

**Comment by ttu** [comment]
Sorry, I had an error in the example. For ListProxy we can't define the type of collection item, so correct declaration is `def _parse_data(ble_data: MacAndRawData, mac_blacklist: ListProxy, allowed_macs: List[str] = []) `

**Comment by terop** [comment]
Now unit tests pass as well.

**Comment by ttu** [comment]
Nice, thank 👍

**Pull request merged**
