### PR TITLE
Handle too short BLE data as valid RuuviTag data

### PR DESCRIPTION
**Pull request by ttu**
Possible fix for https://github.com/ttu/ruuvitag-sensor/issues/147

### CODE REVIEW

**Comment by jcalais** [comment]
Sorry, I'm a bit unfamiliar with what the correct procedure is here. Do you want me to look at an approve the pull request (in which case I need to familiarize myself a bit more with the logic of the library) or do you have more people on the core team who will do it when they have time?

**Comment by jcalais** [comment]
I realise now I don't have any way to approve PRs, so I guess it's up to someone else. Anyway, I read the changes and to me it looks like fairly trivial changes that are unlikely to cause any significant issues with other parts of the library, so to me it looks good! Great work and thanks for the quick fix.

**Comment by ttu** [comment]
Hi! Sorry, I wrote the response in a little hurry and I should have been more clear with my explanation.

There is no team behind this package, just a bunch of RuuviTag users creating issues, fixes, improvements and verifying fixes I make semi-blindly :)

As I can’t reproduce this error, could you try the code in this branch and verify that it works with your setup? After that, I will merge this and release a new version at some point.

**Comment by ttu** [comment]
Couldn't reproduce the issue, but this change didn't break any existing functionality.

**Pull request merged**
