### PR TITLE
Refactor communicators + work of mac os (based on #72)

### PR DESCRIPTION
**Pull request by sergioisidoro**
I wanted to contribute, didn't know exactly where to start. 

I picked up https://github.com/ttu/ruuvitag-sensor/pull/72 made some refactoring, and fixed the tests. Also added some work for tox, so we can test multiple python versions. 

Tried to handle the Keyboard interrupt better on Mac os (it would stay a zombie process blocking the device)

### CODE REVIEW

**Comment by ttu** [comment]
Thanks for the great work!

I have kept the Bleson communication in an own branch as it still is in the early alpha stage and hasn't been updated in a year. It is not yet working correctly in all the cases. I have been checking some other cross platform libraries, but haven't found one yet.

This package also needs to support Python 2.

This PR could be separated to multiple PRs. First we could make the fixes and changes to the master branch and then update the Bleson branch and make it optional to either use Bluez or Bleson. How does that plan sound? Also then if we find some better cross platform library, adding it would be pretty easy.

PRs could be for example:
* RunFlag
* Adaptors (dummy and nix_hci)
* Code cleanup
* Tox (update also developer_notes.md)
* Bleson option when using Python 3
	* Own Adaptor
	* Different DataFormats convert_data functions needed for Bleson and Bluez
	
I really appreciate all the work you have done and hope that you still have interest to split this to smaller pieces. Unfortunately my time is pretty limited at the moment, but I can try to help the best I can.

**Comment by sergioisidoro** [comment]
Hi there ! 
Yes, that sounds good. 

Actually that was my initial idea was to make a PR just for the refactoring (and the first commit is quite easy to cherry-pick) but then I got into the rabbit hole of the bleson because I'm running on mac os. 

I'll break this one down, and if you need some help I can lend a hand.
This is a really interesting project.

**Comment by sergioisidoro** [comment]
Ok, here's the first one: 
https://github.com/ttu/ruuvitag-sensor/pull/91

**Comment by sergioisidoro** [comment]
Second one:
https://github.com/ttu/ruuvitag-sensor/pull/92

**Comment by sergioisidoro** [comment]
Btw, I just came across this project. Could be interesting to get in touch
https://github.com/hulttis

**Comment by ttu** [comment]
@hulttis project looks interesting. Thanks for the tip!

Besides Bleson this is another cross platform BLE project I have been following https://github.com/hbldh/bleak. I still doesn't have macOS support, but when it does, it might be a worth to check out.

**Comment by sergioisidoro** [comment]
This can be closed in favor of #91 #92 
I don't think the keyboard interrupt has been implemented on any other PR, but that can be added later to the draft PR -- and there's an issue for it already anyway -- https://github.com/ttu/ruuvitag-sensor/issues/80

**Pull request closed without merging**
